# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98ca410915037b1e51ab1121621b3911942f6e6f4499e1961d4f3c90132722889b48fd9433f6499601fbd5c66447c249938129306a54e7b3d7c305df7c2b350d

test:
  secret_key_base: 7f2dec1659bec57fdeefcb7ff81d2f5814469657869752d223b20efa11daa8688ce22e38e0d496a273072f6bce3904d5fcba2e8b3e2d2a4a3e2babfe5f576f62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
